variables:
# Agent Azure DevOps
- name: imageAgentAz
  value: 'ubuntu-latest'
# Tfstate
- name: backendServiceArm
  value: 'macmiller(795e0d19-d32c-4ad7-a870-bdc45d74c8d4)'
- name: backendAzureRmResourceGroupName
  value: 'rg-bootcamp-tfstate'
- name: backendAzureRmStorageAccountName 
  value: 'sambabootcampfstate'
- name: backendAzureRmContainerName
  value: 'scmbabootcampfstate'
- name: backendAzureRmKey
  value: 'terraform.tfstate'

stages:

- stage: Terraform
  displayName: Terraform
  jobs:
  - job: Terraform
    displayName: Terraform
    pool:
      vmImage: '$(imageAgentAz)'
    steps:
    - task: TerraformInstaller@0
      displayName: Terraform Installer
      inputs:
        terraformVersion: '1.2.1'

    - task: TerraformTaskV3@3
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(backendServiceArm)'
        backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
        backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(backendAzureRmContainerName)'
        backendAzureRmKey: '$(backendAzureRmKey)'

    - task: TerraformTaskV3@3
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTaskV3@3
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: '$(backendServiceArm)'

    - task: TerraformTaskV3@3
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: '$(backendServiceArm)'

- stage: KubeConfig
  displayName: KubeConfig
  jobs:
  - job: KubeConfig
    displayName: KubeConfig
    pool:
      vmImage: '$(imageAgentAz)'
    steps:
    - task: KubectlInstaller@0
      inputs:
        kubectlVersion: 'latest'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          az login -u $(azLogin) -p $(azPassword)
          az aks get-credentials --resource-group rg-bootcamp --name aks-bootcamp
          cat ~/.kube/config